import type {
  EquipmentType,
  MovementPattern,
  SeedExercise,
} from "./exercise-library";

type LoadType = SeedExercise["loadType"];
type Options = Omit<
  SeedExercise,
  "name" | "family" | "pattern" | "muscles" | "loadType" | "equipment"
>;

const source = {
  name: "Workout Tracker research",
  url: "https://github.com/yuhonas/free-exercise-db",
  license: "Metadata curated from public-domain and professional references",
};

function exercise(
  name: string,
  family: string,
  pattern: MovementPattern,
  muscles: string[],
  loadType: LoadType,
  equipment: EquipmentType[],
  options: Options = {}
): SeedExercise {
  return { name, family, pattern, muscles, loadType, equipment, source, ...options };
}

const e = exercise;

/**
 * Common, trackable variants absent from the original 99-item seed.
 * These are metadata records only—no copied instructions or imagery.
 */
export const expandedExerciseLibrary: SeedExercise[] = [
  // Squat and knee-dominant patterns
  e("Hack Squat Machine", "Squat", "squat", ["quads", "glutes"], "external", ["machine"]),
  e("Smith Machine Back Squat", "Squat", "squat", ["quads", "glutes"], "external", ["smith_machine"]),
  e("Smith Machine Front Squat", "Squat", "squat", ["quads", "glutes", "core"], "external", ["smith_machine"]),
  e("Belt Squat Machine", "Squat", "squat", ["quads", "glutes"], "external", ["machine"]),
  e("Pendulum Squat", "Squat", "squat", ["quads", "glutes"], "external", ["machine"]),
  e("V-Squat Machine", "Squat", "squat", ["quads", "glutes"], "external", ["machine"]),
  e("Sissy Squat", "Squat", "squat", ["quads"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Zercher Squat", "Squat", "squat", ["quads", "glutes", "core"], "barbell", ["barbell", "plates", "rack"]),
  e("Safety Bar Squat", "Squat", "squat", ["quads", "glutes"], "barbell", ["barbell", "plates", "rack"]),
  e("Overhead Squat", "Squat", "squat", ["quads", "glutes", "shoulders", "core"], "barbell", ["barbell", "plates"]),
  e("Landmine Squat", "Squat", "squat", ["quads", "glutes"], "barbell", ["landmine", "barbell", "plates"]),
  e("Medicine Ball Squat", "Squat", "squat", ["quads", "glutes"], "external", ["medicine_ball"]),
  e("Prisoner Squat", "Squat", "squat", ["quads", "glutes"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Jump Squat", "Squat", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Pistol Squat", "Squat", "squat", ["quads", "glutes", "core"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Assisted Pistol Squat", "Squat", "squat", ["quads", "glutes"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted", laterality: "unilateral" } }),
  e("Cossack Squat", "Squat", "squat", ["quads", "glutes", "adductors"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Wall Sit", "Squat", "squat", ["quads", "glutes"], "bodyweight", ["bodyweight"], { metricType: "duration" }),
  e("Heel-Elevated Dumbbell Goblet Squat", "Goblet Squat", "squat", ["quads", "glutes"], "dumbbell", ["dumbbell"]),
  e("Dumbbell Front Squat", "Squat", "squat", ["quads", "glutes", "core"], "dumbbell", ["dumbbell"]),
  e("Double Kettlebell Front Squat", "Squat", "squat", ["quads", "glutes", "core"], "kettlebell", ["kettlebell"]),
  e("Cable Squat", "Squat", "squat", ["quads", "glutes"], "external", ["cable"]),
  e("Smith Machine Box Squat", "Squat", "squat", ["quads", "glutes"], "external", ["smith_machine", "box"]),
  e("Paused Barbell Back Squat", "Squat", "squat", ["quads", "glutes"], "barbell", ["barbell", "plates", "rack"]),
  e("Tempo Barbell Back Squat", "Squat", "squat", ["quads", "glutes"], "barbell", ["barbell", "plates", "rack"]),

  // Hinge and posterior chain
  e("Sumo Deadlift", "Deadlift", "hinge", ["hamstrings", "glutes", "back", "adductors"], "barbell", ["barbell", "plates"]),
  e("Trap Bar Deadlift", "Deadlift", "hinge", ["hamstrings", "glutes", "quads", "back"], "trap_bar", ["trap_bar", "plates"]),
  e("Deficit Barbell Deadlift", "Deadlift", "hinge", ["hamstrings", "glutes", "back"], "barbell", ["barbell", "plates"]),
  e("Barbell Rack Pull", "Deadlift", "hinge", ["back", "glutes", "hamstrings"], "barbell", ["barbell", "plates", "rack"]),
  e("Snatch-Grip Deadlift", "Deadlift", "hinge", ["back", "hamstrings", "glutes"], "barbell", ["barbell", "plates"]),
  e("Barbell Stiff-Leg Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes", "back"], "barbell", ["barbell", "plates"]),
  e("Dumbbell Stiff-Leg Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "dumbbell", ["dumbbell"]),
  e("Single-Leg Dumbbell Romanian Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Single-Leg Kettlebell Romanian Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Cable Pull-Through", "Hip Hinge", "hinge", ["glutes", "hamstrings"], "external", ["cable"]),
  e("Kettlebell Sumo Deadlift", "Deadlift", "hinge", ["hamstrings", "glutes", "adductors"], "kettlebell", ["kettlebell"]),
  e("Trap Bar Romanian Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "trap_bar", ["trap_bar", "plates"]),
  e("Smith Machine Romanian Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "external", ["smith_machine"]),
  e("Smith Machine Good Morning", "Good Morning", "hinge", ["hamstrings", "glutes", "back"], "external", ["smith_machine"]),
  e("Seated Barbell Good Morning", "Good Morning", "hinge", ["hamstrings", "back"], "barbell", ["barbell", "plates", "bench"]),
  e("Barbell Glute Bridge", "Glute Bridge", "hinge", ["glutes"], "barbell", ["barbell", "plates"]),
  e("Dumbbell Hip Thrust", "Hip Thrust", "hinge", ["glutes"], "dumbbell", ["dumbbell", "bench"]),
  e("Smith Machine Hip Thrust", "Hip Thrust", "hinge", ["glutes"], "external", ["smith_machine", "bench"]),
  e("Single-Leg Hip Thrust", "Hip Thrust", "hinge", ["glutes", "hamstrings"], "bodyweight", ["bodyweight", "bench"], { unilateral: true, metricType: "reps" }),
  e("Frog Pump", "Glute Bridge", "hinge", ["glutes"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Nordic Hamstring Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Assisted Nordic Hamstring Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "bodyweight", ["bands", "bodyweight"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Reverse Hyperextension", "Back Extension", "hinge", ["glutes", "hamstrings", "back"], "external", ["machine"]),
  e("45-Degree Back Extension", "Back Extension", "hinge", ["back", "glutes", "hamstrings"], "bodyweight", ["machine"], { metricType: "reps" }),
  e("Cable Romanian Deadlift", "Romanian Deadlift", "hinge", ["hamstrings", "glutes"], "external", ["cable"]),

  // Horizontal pressing and chest isolation
  e("Smith Machine Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps", "shoulders"], "external", ["smith_machine", "bench"]),
  e("Machine Chest Press", "Bench Press", "horizontal_push", ["chest", "triceps", "shoulders"], "external", ["machine"]),
  e("Plate-Loaded Chest Press", "Bench Press", "horizontal_push", ["chest", "triceps", "shoulders"], "external", ["machine", "plates"]),
  e("Decline Barbell Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "barbell", ["barbell", "plates", "bench", "rack"]),
  e("Decline Dumbbell Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Incline Smith Machine Bench Press", "Bench Press", "horizontal_push", ["chest", "shoulders", "triceps"], "external", ["smith_machine", "bench"]),
  e("Close-Grip Dumbbell Bench Press", "Bench Press", "horizontal_push", ["triceps", "chest"], "dumbbell", ["dumbbell", "bench"]),
  e("Neutral-Grip Dumbbell Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Single-Arm Dumbbell Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps", "core"], "dumbbell", ["dumbbell", "bench"], { unilateral: true }),
  e("Alternating Dumbbell Bench Press", "Bench Press", "horizontal_push", ["chest", "triceps", "core"], "dumbbell", ["dumbbell", "bench"], { variantAttributes: { laterality: "alternating" } }),
  e("Dumbbell Squeeze Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Guillotine Press", "Bench Press", "horizontal_push", ["chest", "shoulders"], "barbell", ["barbell", "plates", "bench", "rack"]),
  e("Larsen Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "barbell", ["barbell", "plates", "bench", "rack"]),
  e("Spoto Press", "Bench Press", "horizontal_push", ["chest", "triceps"], "barbell", ["barbell", "plates", "bench", "rack"]),
  e("Incline Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps", "shoulders"], "bodyweight", ["bodyweight", "bench"], { metricType: "reps" }),
  e("Decline Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps", "shoulders"], "bodyweight", ["bodyweight", "bench"], { metricType: "reps" }),
  e("Wide-Grip Push-Up", "Push-Up", "horizontal_push", ["chest", "shoulders", "triceps"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Archer Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps", "core"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Assisted Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps"], "bodyweight", ["bodyweight"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Weighted Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps", "shoulders"], "bodyweight", ["bodyweight", "plates"], { metricType: "weight_reps", loadSemantics: "added_weight", variantAttributes: { assistance: "weighted" } }),
  e("Suspension Push-Up", "Push-Up", "horizontal_push", ["chest", "triceps", "core"], "bodyweight", ["suspension"], { metricType: "reps" }),
  e("Suspension Chest Press", "Chest Press", "horizontal_push", ["chest", "triceps", "core"], "bodyweight", ["suspension"], { metricType: "reps" }),
  e("Cable Chest Press", "Chest Press", "horizontal_push", ["chest", "triceps"], "external", ["cable"]),
  e("Single-Arm Cable Chest Press", "Chest Press", "horizontal_push", ["chest", "triceps", "core"], "external", ["cable"], { unilateral: true }),
  e("Pec Deck Fly", "Chest Fly", "horizontal_push", ["chest"], "external", ["machine"]),
  e("Incline Dumbbell Fly", "Chest Fly", "horizontal_push", ["chest"], "dumbbell", ["dumbbell", "bench"]),
  e("Decline Dumbbell Fly", "Chest Fly", "horizontal_push", ["chest"], "dumbbell", ["dumbbell", "bench"]),
  e("Low-to-High Cable Fly", "Chest Fly", "horizontal_push", ["chest", "shoulders"], "external", ["cable"]),
  e("High-to-Low Cable Fly", "Chest Fly", "horizontal_push", ["chest"], "external", ["cable"]),
  e("Single-Arm Cable Fly", "Chest Fly", "horizontal_push", ["chest"], "external", ["cable"], { unilateral: true }),
  e("Machine Chest Fly", "Chest Fly", "horizontal_push", ["chest"], "external", ["machine"]),

  // Vertical pressing
  e("Smith Machine Shoulder Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "external", ["smith_machine", "bench"]),
  e("Machine Shoulder Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "external", ["machine"]),
  e("Seated Barbell Overhead Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "barbell", ["barbell", "plates", "bench", "rack"]),
  e("Barbell Push Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "legs"], "barbell", ["barbell", "plates", "rack"]),
  e("Dumbbell Push Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "legs"], "dumbbell", ["dumbbell"]),
  e("Single-Arm Dumbbell Shoulder Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Bottom-Up Kettlebell Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "grip"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Half-Kneeling Kettlebell Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Landmine Press", "Overhead Press", "vertical_push", ["shoulders", "chest", "triceps"], "barbell", ["landmine", "barbell", "plates"], { unilateral: true }),
  e("Half-Kneeling Landmine Press", "Overhead Press", "vertical_push", ["shoulders", "chest", "triceps", "core"], "barbell", ["landmine", "barbell", "plates"], { unilateral: true }),
  e("Single-Arm Cable Shoulder Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "external", ["cable"], { unilateral: true }),
  e("Cable Shoulder Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "external", ["cable"]),
  e("Handstand Push-Up", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Wall-Assisted Handstand Push-Up", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "bodyweight", ["bodyweight"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Feet-Elevated Pike Push-Up", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "bodyweight", ["bodyweight", "bench"], { metricType: "reps" }),
  e("Barbell Z Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "barbell", ["barbell", "plates"]),
  e("Dumbbell Z Press", "Overhead Press", "vertical_push", ["shoulders", "triceps", "core"], "dumbbell", ["dumbbell"]),
  e("Behind-the-Neck Barbell Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "barbell", ["barbell", "plates", "rack"]),
  e("Bradford Press", "Overhead Press", "vertical_push", ["shoulders", "triceps"], "barbell", ["barbell", "plates"]),

  // Horizontal pulling and rows
  e("T-Bar Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine"]),
  e("Landmine Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["landmine", "barbell", "plates"]),
  e("Chest-Supported T-Bar Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine", "bench"]),
  e("Machine Seated Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine"]),
  e("Plate-Loaded Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine", "plates"]),
  e("Barbell Seal Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["barbell", "plates", "bench"]),
  e("Chest-Supported Barbell Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["barbell", "plates", "bench"]),
  e("Meadows Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["landmine", "barbell", "plates"], { unilateral: true }),
  e("Single-Arm Landmine Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["landmine", "barbell", "plates"], { unilateral: true }),
  e("Incline Bench Dumbbell Row", "Row", "horizontal_pull", ["back", "biceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Dumbbell Renegade Row", "Row", "horizontal_pull", ["back", "biceps", "core"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Kettlebell Gorilla Row", "Row", "horizontal_pull", ["back", "biceps", "core"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Wide-Grip Seated Cable Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["cable"]),
  e("Neutral-Grip Seated Cable Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["cable"]),
  e("Single-Arm Seated Cable Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["cable"], { unilateral: true }),
  e("Rope Seated Cable Row", "Row", "horizontal_pull", ["back", "biceps"], "external", ["cable"]),
  e("High Row Machine", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine"]),
  e("Low Row Machine", "Row", "horizontal_pull", ["back", "biceps"], "external", ["machine"]),
  e("Suspension Row", "Row", "horizontal_pull", ["back", "biceps", "core"], "bodyweight", ["suspension"], { metricType: "reps" }),
  e("Ring Row", "Row", "horizontal_pull", ["back", "biceps", "core"], "bodyweight", ["suspension"], { metricType: "reps" }),
  e("Underhand Barbell Row", "Row", "horizontal_pull", ["back", "biceps"], "barbell", ["barbell", "plates"]),
  e("Wide-Grip Barbell Row", "Row", "horizontal_pull", ["upper back", "rear delts", "biceps"], "barbell", ["barbell", "plates"]),
  e("Dumbbell Rear Delt Row", "Row", "horizontal_pull", ["rear delts", "upper back", "biceps"], "dumbbell", ["dumbbell"]),
  e("Kettlebell Renegade Row", "Row", "horizontal_pull", ["back", "biceps", "core"], "kettlebell", ["kettlebell"], { unilateral: true }),

  // Vertical pulling
  e("Assisted Pull-Up", "Pull-Up", "vertical_pull", ["back", "biceps"], "external", ["machine", "pullup_bar"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Weighted Pull-Up", "Pull-Up", "vertical_pull", ["back", "biceps"], "bodyweight", ["pullup_bar", "plates"], { metricType: "weight_reps", loadSemantics: "added_weight", variantAttributes: { assistance: "weighted" } }),
  e("Neutral-Grip Pull-Up", "Pull-Up", "vertical_pull", ["back", "biceps"], "bodyweight", ["pullup_bar"], { metricType: "reps" }),
  e("Wide-Grip Pull-Up", "Pull-Up", "vertical_pull", ["back", "biceps"], "bodyweight", ["pullup_bar"], { metricType: "reps" }),
  e("Commando Pull-Up", "Pull-Up", "vertical_pull", ["back", "biceps", "core"], "bodyweight", ["pullup_bar"], { metricType: "reps" }),
  e("Assisted Chin-Up", "Chin-Up", "vertical_pull", ["back", "biceps"], "external", ["machine", "pullup_bar"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Weighted Chin-Up", "Chin-Up", "vertical_pull", ["back", "biceps"], "bodyweight", ["pullup_bar", "plates"], { metricType: "weight_reps", loadSemantics: "added_weight", variantAttributes: { assistance: "weighted" } }),
  e("Close-Grip Lat Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps"], "external", ["cable"]),
  e("Wide-Grip Lat Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps"], "external", ["cable"]),
  e("Neutral-Grip Lat Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps"], "external", ["cable"]),
  e("Reverse-Grip Lat Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps"], "external", ["cable"]),
  e("Single-Arm Lat Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps"], "external", ["cable"], { unilateral: true }),
  e("Kneeling Cable Pulldown", "Lat Pulldown", "vertical_pull", ["back", "biceps", "core"], "external", ["cable"]),
  e("Straight-Arm Cable Pulldown", "Pullover", "vertical_pull", ["lats", "back"], "external", ["cable"]),
  e("Machine Pullover", "Pullover", "vertical_pull", ["lats", "chest"], "external", ["machine"]),
  e("Dumbbell Pullover", "Pullover", "vertical_pull", ["lats", "chest"], "dumbbell", ["dumbbell", "bench"]),
  e("Scapular Pull-Up", "Pull-Up", "vertical_pull", ["back", "shoulders"], "bodyweight", ["pullup_bar"], { metricType: "reps" }),

  // Lunges, split squats, step-ups
  e("Bodyweight Forward Lunge", "Lunge", "lunge", ["quads", "glutes"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Dumbbell Forward Lunge", "Lunge", "lunge", ["quads", "glutes"], "dumbbell", ["dumbbell"], { aliases: ["dumbbell lunge", "dumbbell lunges", "db lunge"], unilateral: true }),
  e("Barbell Walking Lunge", "Lunge", "lunge", ["quads", "glutes"], "barbell", ["barbell", "plates", "rack"], { unilateral: true }),
  e("Bodyweight Walking Lunge", "Lunge", "lunge", ["quads", "glutes"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Barbell Reverse Lunge", "Lunge", "lunge", ["quads", "glutes"], "barbell", ["barbell", "plates", "rack"], { unilateral: true }),
  e("Bodyweight Reverse Lunge", "Lunge", "lunge", ["quads", "glutes"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Curtsy Lunge", "Lunge", "lunge", ["glutes", "quads"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Dumbbell Curtsy Lunge", "Lunge", "lunge", ["glutes", "quads"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Deficit Dumbbell Reverse Lunge", "Lunge", "lunge", ["quads", "glutes"], "dumbbell", ["dumbbell", "box"], { unilateral: true }),
  e("Front-Foot-Elevated Split Squat", "Split Squat", "lunge", ["quads", "glutes"], "dumbbell", ["dumbbell", "box"], { unilateral: true }),
  e("Smith Machine Split Squat", "Split Squat", "lunge", ["quads", "glutes"], "external", ["smith_machine"], { unilateral: true }),
  e("Smith Machine Bulgarian Split Squat", "Bulgarian Split Squat", "lunge", ["quads", "glutes"], "external", ["smith_machine", "bench"], { unilateral: true }),
  e("Barbell Bulgarian Split Squat", "Bulgarian Split Squat", "lunge", ["quads", "glutes"], "barbell", ["barbell", "plates", "bench", "rack"], { unilateral: true }),
  e("Bodyweight Step-Up", "Step-Up", "lunge", ["quads", "glutes"], "bodyweight", ["bodyweight", "box"], { unilateral: true, metricType: "reps" }),
  e("Barbell Step-Up", "Step-Up", "lunge", ["quads", "glutes"], "barbell", ["barbell", "plates", "box", "rack"], { unilateral: true }),
  e("Lateral Step-Up", "Step-Up", "lunge", ["quads", "glutes"], "bodyweight", ["bodyweight", "box"], { unilateral: true, metricType: "reps" }),
  e("Crossover Step-Up", "Step-Up", "lunge", ["glutes", "quads"], "dumbbell", ["dumbbell", "box"], { unilateral: true }),
  e("Kettlebell Walking Lunge", "Lunge", "lunge", ["quads", "glutes"], "kettlebell", ["kettlebell"], { unilateral: true }),

  // Carries
  e("Trap Bar Farmer Carry", "Loaded Carry", "carry", ["grip", "traps", "core"], "trap_bar", ["trap_bar", "plates"], { metricType: "distance_duration" }),
  e("Kettlebell Farmer Carry", "Loaded Carry", "carry", ["grip", "traps", "core"], "kettlebell", ["kettlebell"], { metricType: "distance_duration" }),
  e("Dumbbell Overhead Carry", "Loaded Carry", "carry", ["shoulders", "core", "grip"], "dumbbell", ["dumbbell"], { metricType: "distance_duration" }),
  e("Kettlebell Overhead Carry", "Loaded Carry", "carry", ["shoulders", "core", "grip"], "kettlebell", ["kettlebell"], { metricType: "distance_duration" }),
  e("Waiter Carry", "Loaded Carry", "carry", ["shoulders", "core", "grip"], "dumbbell", ["dumbbell"], { unilateral: true, metricType: "distance_duration" }),
  e("Barbell Front Rack Carry", "Loaded Carry", "carry", ["core", "upper back", "shoulders"], "barbell", ["barbell", "plates", "rack"], { metricType: "distance_duration" }),
  e("Double Kettlebell Front Rack Carry", "Loaded Carry", "carry", ["core", "upper back", "shoulders"], "kettlebell", ["kettlebell"], { metricType: "distance_duration" }),
  e("Bear-Hug Carry", "Loaded Carry", "carry", ["core", "back", "arms"], "external", ["other"], { metricType: "distance_duration" }),
  e("Zercher Carry", "Loaded Carry", "carry", ["core", "back", "arms"], "barbell", ["barbell", "plates"], { metricType: "distance_duration" }),
  e("Plate Pinch Carry", "Loaded Carry", "carry", ["grip", "forearms"], "external", ["plates"], { metricType: "distance_duration" }),
  e("Bottom-Up Kettlebell Carry", "Loaded Carry", "carry", ["grip", "shoulders", "core"], "kettlebell", ["kettlebell"], { unilateral: true, metricType: "distance_duration" }),

  // Core and rotation
  e("Weighted Russian Twist", "Russian Twist", "rotation", ["obliques", "core"], "external", ["medicine_ball"], { loadSemantics: "added_weight" }),
  e("Bodyweight Russian Twist", "Russian Twist", "rotation", ["obliques", "core"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Sit-Up", "Sit-Up", "core", ["abs", "hip flexors"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Weighted Sit-Up", "Sit-Up", "core", ["abs", "hip flexors"], "external", ["plates"]),
  e("Crunch", "Crunch", "core", ["abs"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Bicycle Crunch", "Crunch", "rotation", ["abs", "obliques"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Reverse Crunch", "Crunch", "core", ["abs"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("V-Up", "Leg Raise", "core", ["abs", "hip flexors"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Toe Touch", "Crunch", "core", ["abs"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Lying Leg Raise", "Leg Raise", "core", ["abs", "hip flexors"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Hanging Leg Raise", "Leg Raise", "core", ["abs", "hip flexors"], "bodyweight", ["pullup_bar"], { metricType: "reps" }),
  e("Captain's Chair Knee Raise", "Leg Raise", "core", ["abs", "hip flexors"], "bodyweight", ["machine"], { metricType: "reps" }),
  e("Ab Wheel Rollout", "Rollout", "core", ["abs", "core", "lats"], "external", ["other"], { metricType: "reps" }),
  e("Barbell Rollout", "Rollout", "core", ["abs", "core", "lats"], "barbell", ["barbell", "plates"], { metricType: "reps" }),
  e("Stability Ball Rollout", "Rollout", "core", ["abs", "core"], "bodyweight", ["stability_ball"], { metricType: "reps" }),
  e("Stability Ball Crunch", "Crunch", "core", ["abs"], "bodyweight", ["stability_ball"], { metricType: "reps" }),
  e("Cable Woodchop", "Woodchop", "rotation", ["obliques", "core"], "external", ["cable"], { unilateral: true }),
  e("Band Woodchop", "Woodchop", "rotation", ["obliques", "core"], "band", ["bands"], { unilateral: true }),
  e("Landmine Rotation", "Rotation", "rotation", ["obliques", "core", "shoulders"], "barbell", ["landmine", "barbell", "plates"]),
  e("Medicine Ball Slam", "Medicine Ball Throw", "conditioning", ["core", "lats", "shoulders"], "external", ["medicine_ball"], { activityClass: "conditioning", metricType: "reps" }),
  e("Medicine Ball Rotational Throw", "Medicine Ball Throw", "rotation", ["obliques", "core", "shoulders"], "external", ["medicine_ball"], { activityClass: "conditioning", unilateral: true, metricType: "reps" }),
  e("Dragon Flag", "Leg Raise", "core", ["abs", "core"], "bodyweight", ["bodyweight", "bench"], { metricType: "reps" }),
  e("L-Sit", "Isometric Core", "core", ["abs", "hip flexors", "triceps"], "bodyweight", ["bodyweight"], { metricType: "duration" }),
  e("RKC Plank", "Plank", "core", ["core", "glutes"], "bodyweight", ["bodyweight"], { metricType: "duration" }),
  e("Weighted Plank", "Plank", "core", ["core"], "bodyweight", ["bodyweight", "plates"], { metricType: "duration", loadSemantics: "added_weight", variantAttributes: { assistance: "weighted" } }),
  e("Plank Push-Up", "Plank", "core", ["core", "triceps", "shoulders"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Shoulder-Tap Plank", "Plank", "core", ["core", "shoulders"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Side Plank Hip Lift", "Side Plank", "core", ["obliques", "core"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Copenhagen Plank", "Side Plank", "core", ["adductors", "obliques", "core"], "bodyweight", ["bench"], { unilateral: true, metricType: "duration" }),
  e("Bear Crawl", "Crawl", "locomotion", ["core", "shoulders", "full body"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Mountain Climber", "Mountain Climber", "conditioning", ["core", "cardio", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Cable Pallof Press", "Pallof Press", "core", ["core", "obliques"], "external", ["cable"]),

  // Arms
  e("Straight-Bar Barbell Curl", "Biceps Curl", "isolation_arms", ["biceps"], "barbell", ["barbell", "plates"], { aliases: ["barbell biceps curl"] }),
  e("Reverse Barbell Curl", "Biceps Curl", "isolation_arms", ["biceps", "forearms"], "barbell", ["barbell", "plates"]),
  e("Reverse EZ-Bar Curl", "Biceps Curl", "isolation_arms", ["biceps", "forearms"], "ez_bar", ["ez_bar", "plates"]),
  e("EZ-Bar Preacher Curl", "Biceps Curl", "isolation_arms", ["biceps"], "ez_bar", ["ez_bar", "plates", "bench"]),
  e("Dumbbell Preacher Curl", "Biceps Curl", "isolation_arms", ["biceps"], "dumbbell", ["dumbbell", "bench"], { unilateral: true }),
  e("Machine Preacher Curl", "Biceps Curl", "isolation_arms", ["biceps"], "external", ["machine"]),
  e("Dumbbell Spider Curl", "Biceps Curl", "isolation_arms", ["biceps"], "dumbbell", ["dumbbell", "bench"]),
  e("EZ-Bar Spider Curl", "Biceps Curl", "isolation_arms", ["biceps"], "ez_bar", ["ez_bar", "plates", "bench"]),
  e("Bayesian Cable Curl", "Biceps Curl", "isolation_arms", ["biceps"], "external", ["cable"], { unilateral: true }),
  e("Cable Rope Hammer Curl", "Hammer Curl", "isolation_arms", ["biceps", "forearms"], "external", ["cable"]),
  e("Cross-Body Hammer Curl", "Hammer Curl", "isolation_arms", ["biceps", "forearms"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Zottman Curl", "Biceps Curl", "isolation_arms", ["biceps", "forearms"], "dumbbell", ["dumbbell"]),
  e("Barbell Drag Curl", "Biceps Curl", "isolation_arms", ["biceps"], "barbell", ["barbell", "plates"]),
  e("Incline Hammer Curl", "Hammer Curl", "isolation_arms", ["biceps", "forearms"], "dumbbell", ["dumbbell", "bench"]),
  e("Alternating Dumbbell Curl", "Biceps Curl", "isolation_arms", ["biceps"], "dumbbell", ["dumbbell"], { variantAttributes: { laterality: "alternating" } }),
  e("Cable Concentration Curl", "Biceps Curl", "isolation_arms", ["biceps"], "external", ["cable", "bench"], { unilateral: true }),
  e("Dumbbell Skull Crusher", "Skull Crusher", "isolation_arms", ["triceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Straight-Bar Skull Crusher", "Skull Crusher", "isolation_arms", ["triceps"], "barbell", ["barbell", "plates", "bench"]),
  e("Bench Dip", "Dip", "isolation_arms", ["triceps", "chest", "shoulders"], "bodyweight", ["bench"], { metricType: "reps" }),
  e("Dumbbell Triceps Kickback", "Triceps Extension", "isolation_arms", ["triceps"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Cable Triceps Kickback", "Triceps Extension", "isolation_arms", ["triceps"], "external", ["cable"], { unilateral: true }),
  e("Single-Arm Cable Pushdown", "Triceps Pushdown", "isolation_arms", ["triceps"], "external", ["cable"], { unilateral: true }),
  e("Reverse-Grip Triceps Pushdown", "Triceps Pushdown", "isolation_arms", ["triceps"], "external", ["cable"]),
  e("Rope Triceps Pushdown", "Triceps Pushdown", "isolation_arms", ["triceps"], "external", ["cable"]),
  e("Straight-Bar Triceps Pushdown", "Triceps Pushdown", "isolation_arms", ["triceps"], "external", ["cable"]),
  e("Overhead Cable Triceps Extension", "Triceps Extension", "isolation_arms", ["triceps"], "external", ["cable"]),
  e("Single-Dumbbell Overhead Triceps Extension", "Triceps Extension", "isolation_arms", ["triceps"], "dumbbell", ["dumbbell"]),
  e("Two-Dumbbell Overhead Triceps Extension", "Triceps Extension", "isolation_arms", ["triceps"], "dumbbell", ["dumbbell"]),
  e("Machine Dip", "Dip", "isolation_arms", ["triceps", "chest"], "external", ["machine"]),
  e("Assisted Dip", "Dip", "isolation_arms", ["triceps", "chest"], "external", ["machine", "dip_station"], { metricType: "assisted_reps", loadSemantics: "assistance", variantAttributes: { assistance: "assisted" } }),
  e("Weighted Dip", "Dip", "isolation_arms", ["triceps", "chest"], "bodyweight", ["dip_station", "plates"], { metricType: "weight_reps", loadSemantics: "added_weight", variantAttributes: { assistance: "weighted" } }),
  e("Suspension Triceps Extension", "Triceps Extension", "isolation_arms", ["triceps", "core"], "bodyweight", ["suspension"], { metricType: "reps" }),
  e("Dumbbell Tate Press", "Triceps Extension", "isolation_arms", ["triceps"], "dumbbell", ["dumbbell", "bench"]),
  e("Barbell JM Press", "Triceps Extension", "isolation_arms", ["triceps", "chest"], "barbell", ["barbell", "plates", "bench", "rack"]),

  // Shoulders, rear delts, scapular work
  e("Barbell Upright Row", "Upright Row", "isolation_shoulders", ["shoulders", "traps"], "barbell", ["barbell", "plates"]),
  e("Cable Upright Row", "Upright Row", "isolation_shoulders", ["shoulders", "traps"], "external", ["cable"]),
  e("Dumbbell Upright Row", "Upright Row", "isolation_shoulders", ["shoulders", "traps"], "dumbbell", ["dumbbell"]),
  e("Chest-Supported Dumbbell Reverse Fly", "Rear Delt Fly", "isolation_shoulders", ["rear delts", "upper back"], "dumbbell", ["dumbbell", "bench"]),
  e("Reverse Pec Deck", "Rear Delt Fly", "isolation_shoulders", ["rear delts", "upper back"], "external", ["machine"]),
  e("Cable Rear Delt Fly", "Rear Delt Fly", "isolation_shoulders", ["rear delts", "upper back"], "external", ["cable"]),
  e("Single-Arm Cable Lateral Raise", "Lateral Raise", "isolation_shoulders", ["shoulders"], "external", ["cable"], { unilateral: true }),
  e("Lean-Away Cable Lateral Raise", "Lateral Raise", "isolation_shoulders", ["shoulders"], "external", ["cable"], { unilateral: true }),
  e("Machine Lateral Raise", "Lateral Raise", "isolation_shoulders", ["shoulders"], "external", ["machine"]),
  e("Seated Dumbbell Lateral Raise", "Lateral Raise", "isolation_shoulders", ["shoulders"], "dumbbell", ["dumbbell", "bench"]),
  e("Incline Dumbbell Lateral Raise", "Lateral Raise", "isolation_shoulders", ["shoulders"], "dumbbell", ["dumbbell", "bench"]),
  e("Dumbbell Lu Raise", "Lateral Raise", "isolation_shoulders", ["shoulders", "traps"], "dumbbell", ["dumbbell"]),
  e("Dumbbell Y Raise", "Y Raise", "isolation_shoulders", ["shoulders", "lower traps"], "dumbbell", ["dumbbell"]),
  e("Cable Y Raise", "Y Raise", "isolation_shoulders", ["shoulders", "lower traps"], "external", ["cable"]),
  e("Trap-3 Raise", "Y Raise", "isolation_shoulders", ["lower traps", "rear delts"], "dumbbell", ["dumbbell", "bench"]),
  e("Bent-Over Dumbbell T Raise", "Rear Delt Fly", "isolation_shoulders", ["rear delts", "upper back"], "dumbbell", ["dumbbell"]),
  e("Prone Y Raise", "Y Raise", "isolation_shoulders", ["lower traps", "rear delts"], "bodyweight", ["bench"], { metricType: "reps" }),
  e("Cable Rear Delt Row", "Rear Delt Row", "horizontal_pull", ["rear delts", "upper back"], "external", ["cable"]),
  e("Dumbbell Scaption", "Lateral Raise", "isolation_shoulders", ["shoulders"], "dumbbell", ["dumbbell"]),
  e("Dumbbell Cuban Press", "External Rotation", "isolation_shoulders", ["rotator cuff", "shoulders"], "dumbbell", ["dumbbell"]),
  e("Band External Rotation", "External Rotation", "isolation_shoulders", ["rotator cuff"], "band", ["bands"]),
  e("Cable External Rotation", "External Rotation", "isolation_shoulders", ["rotator cuff"], "external", ["cable"], { unilateral: true }),
  e("Dumbbell External Rotation", "External Rotation", "isolation_shoulders", ["rotator cuff"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Wall Slide", "Scapular Control", "mobility", ["shoulders", "upper back"], "bodyweight", ["bodyweight"], { activityClass: "activation", metricType: "reps" }),
  e("Scapular Push-Up", "Scapular Control", "horizontal_push", ["shoulders", "serratus"], "bodyweight", ["bodyweight"], { activityClass: "activation", metricType: "reps" }),

  // Leg isolation
  e("Seated Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "external", ["machine"]),
  e("Smith Machine Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "external", ["smith_machine"]),
  e("Leg Press Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "external", ["machine"]),
  e("Donkey Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "bodyweight", ["machine"], { metricType: "reps" }),
  e("Single-Leg Bodyweight Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "bodyweight", ["bodyweight"], { unilateral: true, metricType: "reps" }),
  e("Single-Leg Dumbbell Calf Raise", "Calf Raise", "isolation_legs", ["calves"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Tibialis Raise", "Tibialis Raise", "isolation_legs", ["tibialis anterior"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Seated Leg Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "external", ["machine"]),
  e("Lying Leg Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "external", ["machine"]),
  e("Standing Leg Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "external", ["machine"], { unilateral: true }),
  e("Cable Leg Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "external", ["cable"], { unilateral: true }),
  e("Hip Abduction Machine", "Hip Abduction", "isolation_legs", ["glutes", "abductors"], "external", ["machine"]),
  e("Hip Adduction Machine", "Hip Adduction", "isolation_legs", ["adductors"], "external", ["machine"]),
  e("Cable Hip Abduction", "Hip Abduction", "isolation_legs", ["glutes", "abductors"], "external", ["cable"], { unilateral: true }),
  e("Cable Hip Adduction", "Hip Adduction", "isolation_legs", ["adductors"], "external", ["cable"], { unilateral: true }),
  e("Glute Kickback Machine", "Hip Extension", "isolation_legs", ["glutes"], "external", ["machine"], { unilateral: true }),
  e("Cable Glute Kickback", "Hip Extension", "isolation_legs", ["glutes"], "external", ["cable"], { unilateral: true }),
  e("Reverse Nordic Curl", "Knee Extension", "isolation_legs", ["quads"], "bodyweight", ["bodyweight"], { metricType: "reps" }),
  e("Band Terminal Knee Extension", "Knee Extension", "isolation_legs", ["quads"], "band", ["bands"], { unilateral: true }),
  e("Single-Leg Extension", "Knee Extension", "isolation_legs", ["quads"], "external", ["machine"], { unilateral: true }),
  e("Single-Leg Curl", "Leg Curl", "isolation_legs", ["hamstrings"], "external", ["machine"], { unilateral: true }),

  // Olympic lifting and power
  e("Barbell Power Clean", "Clean", "olympic_lift", ["full body", "glutes", "back", "shoulders"], "barbell", ["barbell", "plates"]),
  e("Hang Power Clean", "Clean", "olympic_lift", ["full body", "glutes", "back", "shoulders"], "barbell", ["barbell", "plates"]),
  e("Barbell Clean", "Clean", "olympic_lift", ["full body", "glutes", "back", "shoulders"], "barbell", ["barbell", "plates"]),
  e("Kettlebell Clean", "Clean", "olympic_lift", ["full body", "glutes", "shoulders"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Dumbbell Clean", "Clean", "olympic_lift", ["full body", "glutes", "shoulders"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Barbell Power Snatch", "Snatch", "olympic_lift", ["full body", "shoulders", "back", "glutes"], "barbell", ["barbell", "plates"]),
  e("Hang Power Snatch", "Snatch", "olympic_lift", ["full body", "shoulders", "back", "glutes"], "barbell", ["barbell", "plates"]),
  e("Barbell Snatch", "Snatch", "olympic_lift", ["full body", "shoulders", "back", "glutes"], "barbell", ["barbell", "plates"]),
  e("Clean and Jerk", "Clean and Jerk", "olympic_lift", ["full body"], "barbell", ["barbell", "plates"]),
  e("Push Jerk", "Jerk", "olympic_lift", ["shoulders", "triceps", "legs"], "barbell", ["barbell", "plates"]),
  e("Split Jerk", "Jerk", "olympic_lift", ["shoulders", "triceps", "legs"], "barbell", ["barbell", "plates"]),
  e("Barbell High Pull", "High Pull", "olympic_lift", ["traps", "shoulders", "back"], "barbell", ["barbell", "plates"]),
  e("Kettlebell Snatch", "Snatch", "olympic_lift", ["full body", "shoulders"], "kettlebell", ["kettlebell"], { unilateral: true }),
  e("Dumbbell Snatch", "Snatch", "olympic_lift", ["full body", "shoulders"], "dumbbell", ["dumbbell"], { unilateral: true }),
  e("Kettlebell Clean and Press", "Clean and Press", "olympic_lift", ["full body", "shoulders", "triceps"], "kettlebell", ["kettlebell"], { unilateral: true }),

  // Plyometrics and conditioning
  e("Box Jump", "Jump", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["box"], { activityClass: "conditioning", metricType: "reps" }),
  e("Broad Jump", "Jump", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Depth Jump", "Jump", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["box"], { activityClass: "conditioning", metricType: "reps" }),
  e("Tuck Jump", "Jump", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Skater Jump", "Jump", "plyometric", ["glutes", "quads", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", unilateral: true, metricType: "reps" }),
  e("Jumping Lunge", "Lunge", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", unilateral: true, metricType: "reps" }),
  e("Split Squat Jump", "Split Squat", "plyometric", ["quads", "glutes", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", unilateral: true, metricType: "reps" }),
  e("Plyometric Push-Up", "Push-Up", "plyometric", ["chest", "triceps", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Medicine Ball Chest Pass", "Medicine Ball Throw", "plyometric", ["chest", "triceps", "shoulders"], "external", ["medicine_ball"], { activityClass: "conditioning", metricType: "reps" }),
  e("Lateral Bound", "Jump", "plyometric", ["glutes", "quads", "calves"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", unilateral: true, metricType: "reps" }),
  e("Outdoor Running", "Running", "locomotion", ["cardio", "legs"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Treadmill Running", "Running", "locomotion", ["cardio", "legs"], "bodyweight", ["treadmill"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Stationary Bike", "Cycling", "conditioning", ["cardio", "legs"], "external", ["stationary_bike"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Air Bike", "Cycling", "conditioning", ["cardio", "full body"], "external", ["stationary_bike"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Stair Climber", "Stair Climbing", "conditioning", ["cardio", "quads", "glutes"], "external", ["stair_machine"], { activityClass: "conditioning", metricType: "duration" }),
  e("Sled Push", "Sled", "locomotion", ["quads", "glutes", "calves", "shoulders"], "external", ["sled", "plates"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Sled Pull", "Sled", "locomotion", ["back", "legs", "arms"], "external", ["sled", "plates"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Battle Ropes", "Battle Ropes", "conditioning", ["cardio", "shoulders", "arms"], "external", ["battle_rope"], { activityClass: "conditioning", metricType: "duration" }),
  e("High Knees", "Running", "conditioning", ["cardio", "legs"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "duration" }),
  e("Jumping Jack", "Jumping Jack", "conditioning", ["cardio", "full body"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "reps" }),
  e("Shuttle Run", "Running", "locomotion", ["cardio", "legs"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Ski Erg", "Ski Erg", "conditioning", ["cardio", "back", "arms"], "external", ["machine"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Swimming", "Swimming", "conditioning", ["cardio", "full body"], "bodyweight", ["other"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Walking", "Walking", "locomotion", ["cardio", "legs"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Incline Treadmill Walk", "Walking", "locomotion", ["cardio", "legs", "glutes"], "bodyweight", ["treadmill"], { activityClass: "conditioning", metricType: "distance_duration" }),
  e("Running in Place", "Running", "conditioning", ["cardio", "legs"], "bodyweight", ["bodyweight"], { activityClass: "conditioning", metricType: "duration" }),

  // Mobility, stretches, and warm-up drills
  e("Arm Circles", "Shoulder Mobility", "mobility", ["shoulders"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "duration" }),
  e("Arm Crosses", "Shoulder Mobility", "mobility", ["chest", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "duration" }),
  e("Cat-Cow Stretch", "Spinal Mobility", "mobility", ["back", "core"], "bodyweight", ["bodyweight"], { activityClass: "mobility", metricType: "duration" }),
  e("Doorway Chest Stretch", "Chest Stretch", "stretch", ["chest", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "stretch", metricType: "duration" }),
  e("Dynamic Chest Stretch", "Chest Stretch", "mobility", ["chest", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "duration" }),
  e("Ankle Circles", "Ankle Mobility", "mobility", ["ankles", "calves"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "duration" }),
  e("Leg Swings", "Hip Mobility", "mobility", ["hips", "hamstrings", "glutes"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "reps" }),
  e("Bodyweight Hip Hinge Drill", "Hip Hinge", "mobility", ["hamstrings", "glutes", "back"], "bodyweight", ["bodyweight"], { activityClass: "activation", metricType: "reps" }),
  e("World's Greatest Stretch", "Full-Body Mobility", "mobility", ["hips", "hamstrings", "back", "shoulders"], "bodyweight", ["bodyweight"], { activityClass: "mobility", metricType: "duration" }),
  e("Thoracic Rotation", "Spinal Mobility", "rotation", ["upper back", "core"], "bodyweight", ["bodyweight"], { activityClass: "mobility", unilateral: true, metricType: "reps" }),
  e("90/90 Hip Switch", "Hip Mobility", "mobility", ["hips", "glutes"], "bodyweight", ["bodyweight"], { activityClass: "mobility", metricType: "reps" }),
  e("Kneeling Hip Flexor Stretch", "Hip Stretch", "stretch", ["hip flexors", "quads"], "bodyweight", ["bodyweight"], { activityClass: "stretch", unilateral: true, metricType: "duration" }),
  e("Couch Stretch", "Hip Stretch", "stretch", ["hip flexors", "quads"], "bodyweight", ["bench"], { activityClass: "stretch", unilateral: true, metricType: "duration" }),
  e("Hamstring Stretch", "Hamstring Stretch", "stretch", ["hamstrings"], "bodyweight", ["bodyweight"], { activityClass: "stretch", metricType: "duration" }),
  e("Calf Stretch", "Calf Stretch", "stretch", ["calves"], "bodyweight", ["bodyweight"], { activityClass: "stretch", unilateral: true, metricType: "duration" }),
  e("Child's Pose", "Spinal Mobility", "stretch", ["back", "shoulders", "hips"], "bodyweight", ["bodyweight"], { activityClass: "stretch", metricType: "duration" }),
  e("Cobra Stretch", "Spinal Mobility", "stretch", ["abs", "back"], "bodyweight", ["bodyweight"], { activityClass: "stretch", metricType: "duration" }),
  e("Downward Dog", "Full-Body Mobility", "stretch", ["shoulders", "hamstrings", "calves"], "bodyweight", ["bodyweight"], { activityClass: "stretch", metricType: "duration" }),
  e("Pigeon Stretch", "Hip Stretch", "stretch", ["glutes", "hips"], "bodyweight", ["bodyweight"], { activityClass: "stretch", unilateral: true, metricType: "duration" }),
  e("Figure-Four Stretch", "Hip Stretch", "stretch", ["glutes", "hips"], "bodyweight", ["bodyweight"], { activityClass: "stretch", unilateral: true, metricType: "duration" }),
  e("Band Shoulder Dislocate", "Shoulder Mobility", "mobility", ["shoulders", "chest"], "band", ["bands"], { activityClass: "warmup", metricType: "reps" }),
  e("Wall Angel", "Scapular Control", "mobility", ["shoulders", "upper back"], "bodyweight", ["bodyweight"], { activityClass: "activation", metricType: "reps" }),
  e("Clamshell", "Hip Activation", "isolation_legs", ["glutes", "abductors"], "bodyweight", ["bodyweight"], { activityClass: "activation", unilateral: true, metricType: "reps" }),
  e("Fire Hydrant", "Hip Activation", "isolation_legs", ["glutes", "abductors"], "bodyweight", ["bodyweight"], { activityClass: "activation", unilateral: true, metricType: "reps" }),
  e("Banded Lateral Walk", "Hip Activation", "locomotion", ["glutes", "abductors"], "band", ["bands"], { activityClass: "activation", metricType: "reps" }),
  e("Banded Monster Walk", "Hip Activation", "locomotion", ["glutes", "abductors"], "band", ["bands"], { activityClass: "activation", metricType: "reps" }),
  e("Neck Rotation", "Neck Mobility", "mobility", ["neck"], "bodyweight", ["bodyweight"], { activityClass: "mobility", metricType: "duration" }),
  e("Wrist Circles", "Wrist Mobility", "mobility", ["wrists", "forearms"], "bodyweight", ["bodyweight"], { activityClass: "warmup", metricType: "duration" }),
  e("Foam Roll Quadriceps", "Soft Tissue Work", "mobility", ["quads"], "bodyweight", ["foam_roller"], { activityClass: "mobility", metricType: "duration" }),
  e("Foam Roll Hamstrings", "Soft Tissue Work", "mobility", ["hamstrings"], "bodyweight", ["foam_roller"], { activityClass: "mobility", metricType: "duration" }),
  e("Foam Roll Upper Back", "Soft Tissue Work", "mobility", ["upper back"], "bodyweight", ["foam_roller"], { activityClass: "mobility", metricType: "duration" }),
];
