import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import type { PgliteDatabase } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import * as schema from "@/db/schema";
import { healthActivities, userProfiles, users } from "@/db/schema";
import { normalizeActivityInput } from "@/services/activities";
import {
  getHistoryCalendarRecords,
  getHistoryReport,
} from "@/services/history-report";
import { getActivityReport } from "@/services/activity-report";
import { buildTrainingDigest, renderCoachingBrief } from "@/services/digest";
import {
  BACKUP_SCHEMA_VERSION,
  buildActivitiesCsv,
  buildJsonBackup,
} from "@/services/export";

describe("health activity database integration", () => {
  let client: PGlite;
  let db: PgliteDatabase<typeof schema>;
  let userId: string;

  beforeAll(async () => {
    client = new PGlite();
    db = drizzle(client, { schema });
    await migrate(db, { migrationsFolder: "./src/db/migrations" });
    [{ id: userId }] = await db
      .insert(users)
      .values({ email: "activity-test@example.com" })
      .returning({ id: users.id });
    await db.insert(userProfiles).values({ userId });

    const activity = normalizeActivityInput(
      {
        activityType: "walk",
        title: "Power walk",
        startedAtISO: "2026-07-10T14:00:00.000Z",
        timezone: "America/Toronto",
        durationMinutes: 42,
        distanceValue: 3.5,
        distanceUnit: "km",
        intensity: "moderate",
        elevationValue: 40,
        elevationUnit: "m",
        averageHeartRateBpm: 116,
        energyKcal: 280,
        notes: "Steady effort.",
      },
      new Date("2026-07-10T18:00:00.000Z")
    );
    await db.insert(healthActivities).values({ userId, ...activity });
  }, 30_000);

  afterAll(async () => {
    await client.close();
  });

  it("returns activities as calendar records without creating workouts", async () => {
    const [calendar, report, activityReport] = await Promise.all([
      getHistoryCalendarRecords(db, userId),
      getHistoryReport(db, userId, "all", 3),
      getActivityReport(
        db,
        userId,
        "all",
        new Date("2026-07-11T18:00:00.000Z")
      ),
    ]);

    expect(calendar).toHaveLength(1);
    expect(calendar[0]).toMatchObject({
      recordType: "activity",
      name: "Power walk",
      durationMin: 42,
      distanceKm: 3.5,
      timezone: "America/Toronto",
      calendarDateKey: "2026-07-10",
    });
    expect(report.overview.completedSessions).toBe(0);
    expect(report.overview.workingSets).toBe(0);
    expect(report.lenses).toHaveLength(5);
    expect(
      report.lenses.every((lens) => lens.decision.supported === false)
    ).toBe(true);
    expect(JSON.stringify(report.lenses)).not.toContain("Power walk");
    expect(JSON.stringify(report.lenses)).not.toContain("3.5 km");
    expect(JSON.stringify(report.lenses)).not.toContain("42 min");
    expect(activityReport.overview).toMatchObject({
      totalActivities: 1,
      totalMinutes: 42,
      totalDistanceKm: 3.5,
    });
  });

  it("gives Coach labelled activity evidence without inventing strength data", async () => {
    const digest = await buildTrainingDigest(
      db,
      userId,
      new Date("2026-07-01T00:00:00.000Z"),
      new Date("2026-07-11T18:00:00.000Z")
    );
    const brief = renderCoachingBrief(digest);

    expect(digest.sessions).toHaveLength(0);
    expect(digest.cadence.completedSessions).toBe(0);
    expect(digest.independentActivities.overview.totalActivities).toBe(1);
    expect(digest.independentActivities.recent[0]).toMatchObject({
      title: "Power walk",
      distanceKm: 3.5,
      source: "manual",
    });
    expect(brief).toContain(
      "Independent health activities (separate from strength progression)"
    );
    expect(brief).toContain("Power walk, 42 min, 3.5 km");
    expect(brief).toContain(
      "the broad inventory list does not prove that any exercise works with an item",
    );
    expect(brief).toContain("_Generated by Repbook.");
  });

  it("includes normalized and original activity measurements in exports", async () => {
    const [csv, backup] = await Promise.all([
      buildActivitiesCsv(db, userId, null),
      buildJsonBackup(db, userId),
    ]);

    expect(csv).toContain("activity_type");
    expect(csv).toContain("Power walk");
    expect(csv).toContain("3.5,km,3.5");
    expect(backup.schemaVersion).toBe(BACKUP_SCHEMA_VERSION);
    expect(backup.canonical.tables.health_activities).toHaveLength(1);
  });

  it("enforces core numeric checks in Postgres", async () => {
    const existing = await db.query.healthActivities.findFirst();
    expect(existing).toBeTruthy();

    await expect(
      db.insert(healthActivities).values({
        ...existing!,
        id: crypto.randomUUID(),
        durationSeconds: 0,
        fingerprint: "invalid-duration",
      })
    ).rejects.toThrow();
  });

  it("prevents duplicate source record identities", async () => {
    const base = await db.query.healthActivities.findFirst();
    expect(base).toBeTruthy();

    await db.insert(healthActivities).values({
      ...base!,
      id: crypto.randomUUID(),
      source: "apple_health",
      sourceRecordId: "apple-activity-1",
      fingerprint: "apple-fingerprint-1",
    });
    await expect(
      db.insert(healthActivities).values({
        ...base!,
        id: crypto.randomUUID(),
        source: "apple_health",
        sourceRecordId: "apple-activity-1",
        fingerprint: "apple-fingerprint-2",
      })
    ).rejects.toThrow();
  });

  it("prevents duplicate manual activity fingerprints", async () => {
    const base = await db.query.healthActivities.findFirst();
    expect(base).toBeTruthy();

    await expect(
      db.insert(healthActivities).values({
        ...base!,
        id: crypto.randomUUID(),
      })
    ).rejects.toThrow();
  });
});
