import { getDb } from "@/db";
import {
  completedSets,
  exercises,
  historyImportBatches,
  importEvents,
  recordVersions,
  sessionExercises,
  sessionOccurrences,
  userProfiles,
  users,
  workoutSessions,
} from "@/db/schema";
import {
  V2_H01_HISTORY_EMAIL,
  V2_H01_HISTORY_IDS as ids,
} from "./v2-h01-history";

async function main() {
  const db = await getDb();
  const timezone = "America/Toronto";

  await db.insert(users).values({
    id: ids.user,
    email: V2_H01_HISTORY_EMAIL,
    name: "H01 History fixture",
  });
  await db.insert(userProfiles).values({
    userId: ids.user,
    timezone,
    unit: "lb",
    setupCompletedAt: new Date("2026-07-01T14:00:00.000Z"),
  });

  await db.insert(importEvents).values({
    id: ids.importEvent,
    userId: ids.user,
    source: "csv",
    rawPayload: "synthetic H01 browser fixture",
    payloadSha256: "h01-fixture",
    parsedPayload: {},
    confirmedPayload: { schemaVersion: "1", resolutions: [] },
    status: "confirmed",
    rawRedactedAt: new Date("2026-08-01T13:00:00.000Z"),
  });
  await db.insert(historyImportBatches).values({
    id: ids.importBatch,
    userId: ids.user,
    importEventId: ids.importEvent,
    source: "hevy",
    originalFilename: "h01-synthetic.csv",
    fileHash: "h01-synthetic-file-hash",
    timezone,
    status: "confirmed",
    summary: {
      workouts: 1,
      exerciseOccurrences: 1,
      sets: 4,
      warmupSets: 1,
      supersetGroups: 0,
      excludedExercises: 0,
      warnings: 1,
    },
    confirmedAt: new Date("2026-08-01T13:05:00.000Z"),
  });

  await db.insert(exercises).values([
    {
      id: ids.plannedExercise,
      name: "H01 Loaded Bulgarian Split Squat",
      movementPattern: "lunge",
      primaryMuscles: ["quads", "glutes"],
      loadType: "dumbbell",
      metricType: "weight_reps",
      loadSemantics: "per_implement",
    },
    {
      id: ids.performedExercise,
      name: "H01 Bodyweight Bulgarian Split Squat",
      movementPattern: "lunge",
      primaryMuscles: ["quads", "glutes"],
      loadType: "bodyweight",
      metricType: "reps",
      loadSemantics: "bodyweight",
    },
  ]);

  await db.insert(workoutSessions).values([
    {
      id: ids.importedSession,
      userId: ids.user,
      importBatchId: ids.importBatch,
      templateName: "Imported performed-first workout",
      source: "hevy",
      sourceWorkoutKey: "hevy-workout-h01",
      historyRevision: 2,
      status: "completed",
      startedAt: new Date("2026-08-01T14:00:00.000Z"),
      finishedAt: new Date("2026-08-01T14:42:00.000Z"),
      timezone,
      localDate: "2026-08-01",
    },
    {
      id: ids.finishedEarlySession,
      userId: ids.user,
      templateName: "Finished early workout",
      source: "compiler",
      status: "completed",
      startedAt: new Date("2026-08-02T14:00:00.000Z"),
      finishedAt: new Date("2026-08-02T14:20:00.000Z"),
      timezone,
      localDate: "2026-08-02",
    },
    {
      id: ids.abandonedSession,
      userId: ids.user,
      templateName: "Abandoned evidence workout",
      source: "tracker",
      status: "abandoned",
      startedAt: new Date("2026-08-03T14:00:00.000Z"),
      finishedAt: new Date("2026-08-03T14:12:00.000Z"),
      timezone,
      localDate: "2026-08-03",
    },
    {
      id: ids.activeSession,
      userId: ids.user,
      templateName: "Active H01 redirect workout",
      source: "tracker",
      status: "in_progress",
      startedAt: new Date("2026-08-04T14:00:00.000Z"),
      timezone,
      localDate: "2026-08-04",
    },
  ]);

  await db.insert(sessionExercises).values([
    {
      id: ids.importedSessionExercise,
      sessionId: ids.importedSession,
      exerciseId: ids.performedExercise,
      sourceExerciseKey: "hevy-bodyweight-bss",
      sourceExerciseName: "Bulgarian Split Squat",
      prescribedSemanticsVersion: 1,
      prescribedExerciseName: "Loaded Bulgarian Split Squat",
      prescribedMetricType: "weight_reps",
      prescribedLoadType: "dumbbell",
      prescribedLoadSemantics: "per_implement",
      modificationType: "substituted",
      substitutedForExerciseId: ids.plannedExercise,
      substitutionReason: "equipment_busy",
      substitutedAt: new Date("2026-08-01T14:02:00.000Z"),
      orderIdx: 0,
      targetSets: 2,
      targetRepsMin: 8,
      targetRepsMax: 12,
      targetLoad: 40,
      targetLoadUnit: "lb",
      warmupNotes: "Original Program guidance: rehearse balance before working sets.",
    },
    {
      id: ids.finishedSessionExercise,
      sessionId: ids.finishedEarlySession,
      exerciseId: ids.performedExercise,
      prescribedSemanticsVersion: 1,
      prescribedExerciseName: "Bodyweight Bulgarian Split Squat",
      prescribedMetricType: "reps",
      prescribedLoadType: "bodyweight",
      prescribedLoadSemantics: "bodyweight",
      orderIdx: 0,
      targetSets: 2,
      targetRepsMin: 8,
      targetRepsMax: 10,
    },
    {
      id: ids.abandonedSessionExercise,
      sessionId: ids.abandonedSession,
      exerciseId: ids.performedExercise,
      prescribedSemanticsVersion: 1,
      prescribedExerciseName: "Bodyweight Bulgarian Split Squat",
      prescribedMetricType: "reps",
      prescribedLoadType: "bodyweight",
      prescribedLoadSemantics: "bodyweight",
      orderIdx: 0,
      targetSets: 2,
      targetRepsMin: 6,
      targetRepsMax: 8,
    },
  ]);

  await db.insert(completedSets).values([
    {
      id: ids.importedSet,
      sessionExerciseId: ids.importedSessionExercise,
      setNo: 1,
      reps: 11,
      metricType: "reps",
      performedSemanticsVersion: 1,
      performedLoadType: "bodyweight",
      performedLoadSemantics: "bodyweight",
      observedCompletedAt: new Date("2026-08-01T14:12:00.000Z"),
      observedCompletionProvenance: "import_source",
      observedCompletionQuality: "trustworthy",
      note: "Supported imported bodyweight evidence",
    },
    {
      id: ids.importedExtraSet,
      sessionExerciseId: ids.importedSessionExercise,
      setNo: 2,
      reps: 8,
      metricType: "reps",
      performedSemanticsVersion: 1,
      performedLoadType: "bodyweight",
      performedLoadSemantics: "bodyweight",
      observedCompletedAt: new Date("2026-08-01T14:18:00.000Z"),
      observedCompletionProvenance: "import_source",
      observedCompletionQuality: "trustworthy",
      note: "Extra imported working set",
    },
    {
      id: ids.importedLegacySet,
      sessionExerciseId: ids.importedSessionExercise,
      setNo: 3,
      reps: 9,
      metricType: "reps",
      performedSemanticsVersion: null,
      performedLoadType: null,
      performedLoadSemantics: null,
      observedCompletionProvenance: "unknown",
      observedCompletionQuality: "unknown",
      note: "Legacy acknowledged working set",
    },
    {
      id: ids.importedUnlinkedSet,
      sessionExerciseId: ids.importedSessionExercise,
      setNo: 4,
      weight: 50,
      weightUnit: "lb",
      reps: 10,
      metricType: "weight_reps",
      performedSemanticsVersion: null,
      performedLoadType: null,
      performedLoadSemantics: null,
      sourceSetIndex: 9,
      sourceRow: 41,
      note: "Retained unlinked import row",
    },
    {
      id: ids.finishedSet,
      sessionExerciseId: ids.finishedSessionExercise,
      setNo: 1,
      reps: 8,
      metricType: "reps",
      performedSemanticsVersion: 1,
      performedLoadType: "bodyweight",
      performedLoadSemantics: "bodyweight",
    },
    {
      id: ids.abandonedSet,
      sessionExerciseId: ids.abandonedSessionExercise,
      setNo: 1,
      reps: 6,
      metricType: "reps",
      performedSemanticsVersion: 1,
      performedLoadType: "bodyweight",
      performedLoadSemantics: "bodyweight",
      note: "Acknowledged before abandonment",
    },
  ]);

  await db.insert(sessionOccurrences).values([
    {
      id: ids.importedWarmupOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "exercise_warmup",
      origin: "imported",
      sequenceIdx: 0,
      kindOrdinal: 0,
      label: "Balance rehearsal",
      plannedExerciseId: ids.plannedExercise,
      plannedRepsMin: 5,
      plannedRepsMax: 5,
      outcome: "completed",
      outcomeNote: "Completed before the imported working sets",
      revision: 1,
      resolvedAt: new Date("2026-08-01T14:07:00.000Z"),
    },
    {
      id: ids.importedPlannedOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 1,
      kindOrdinal: 0,
      plannedExerciseId: ids.plannedExercise,
      plannedRepsMin: 8,
      plannedRepsMax: 12,
      plannedLoad: 40,
      plannedLoadUnit: "lb",
      outcome: "completed",
      revision: 1,
      resolvedAt: new Date("2026-08-01T14:12:00.000Z"),
      completedSetId: ids.importedSet,
    },
    {
      id: ids.importedExtraOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "working_set",
      origin: "ad_hoc",
      sequenceIdx: 2,
      kindOrdinal: 1,
      label: "Extra set 1",
      plannedExerciseId: ids.performedExercise,
      outcome: "completed",
      revision: 1,
      resolvedAt: new Date("2026-08-01T14:18:00.000Z"),
      completedSetId: ids.importedExtraSet,
    },
    {
      id: ids.importedLegacyOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "working_set",
      origin: "legacy",
      sequenceIdx: 3,
      kindOrdinal: 2,
      plannedExerciseId: ids.performedExercise,
      outcome: "completed",
      revision: 1,
      resolvedAt: new Date("2026-08-01T14:20:00.000Z"),
      completedSetId: ids.importedLegacySet,
    },
    {
      id: ids.importedSkippedOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 4,
      kindOrdinal: 3,
      plannedExerciseId: ids.plannedExercise,
      plannedRepsMin: 8,
      plannedRepsMax: 12,
      plannedLoad: 40,
      plannedLoadUnit: "lb",
      outcome: "skipped",
      outcomeReason: "time",
      revision: 1,
      resolvedAt: new Date("2026-08-01T14:21:00.000Z"),
    },
    {
      id: ids.importedUnknownOccurrence,
      sessionId: ids.importedSession,
      sessionExerciseId: ids.importedSessionExercise,
      kind: "working_set",
      origin: "legacy",
      sequenceIdx: 5,
      kindOrdinal: 4,
      plannedExerciseId: ids.plannedExercise,
      outcome: "legacy_unrecorded",
    },
    {
      id: ids.finishedOccurrence,
      sessionId: ids.finishedEarlySession,
      sessionExerciseId: ids.finishedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 0,
      kindOrdinal: 0,
      plannedExerciseId: ids.performedExercise,
      plannedRepsMin: 8,
      plannedRepsMax: 10,
      outcome: "completed",
      revision: 1,
      resolvedAt: new Date("2026-08-02T14:10:00.000Z"),
      completedSetId: ids.finishedSet,
    },
    {
      id: ids.finishedAbandonedOccurrence,
      sessionId: ids.finishedEarlySession,
      sessionExerciseId: ids.finishedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 1,
      kindOrdinal: 1,
      plannedExerciseId: ids.performedExercise,
      plannedRepsMin: 8,
      plannedRepsMax: 10,
      outcome: "abandoned",
      outcomeReason: "finished_early",
      outcomeNote: "Time budget ended",
      revision: 1,
      resolvedAt: new Date("2026-08-02T14:20:00.000Z"),
    },
    {
      id: ids.abandonedOccurrence,
      sessionId: ids.abandonedSession,
      sessionExerciseId: ids.abandonedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 0,
      kindOrdinal: 0,
      plannedExerciseId: ids.performedExercise,
      plannedRepsMin: 6,
      plannedRepsMax: 8,
      outcome: "completed",
      revision: 1,
      resolvedAt: new Date("2026-08-03T14:08:00.000Z"),
      completedSetId: ids.abandonedSet,
    },
    {
      id: ids.abandonedRemainingOccurrence,
      sessionId: ids.abandonedSession,
      sessionExerciseId: ids.abandonedSessionExercise,
      kind: "working_set",
      origin: "planned",
      sequenceIdx: 1,
      kindOrdinal: 1,
      plannedExerciseId: ids.performedExercise,
      plannedRepsMin: 6,
      plannedRepsMax: 8,
      outcome: "abandoned",
      outcomeReason: "workout_abandoned",
      revision: 1,
      resolvedAt: new Date("2026-08-03T14:12:00.000Z"),
    },
  ]);

  const correctionEnvelope = {
    schemaVersion: 1,
    writerVersion: "repbook-v2-t02/1",
    category: "measurement_entry",
    reasonNote: "Corrected the imported repetition count",
    actorType: "owner",
    source: "workout_history",
    decidedAt: "2026-08-01T16:00:00.000Z",
    decisionTimezone: timezone,
    decisionLocalDate: "2026-08-01",
    sourceHistoryRevision: 0,
    resultHistoryRevision: 1,
    sourceLedgerRevision: 0,
    resultLedgerRevision: 1,
    dependentConclusions: "recompute_queued",
    expiredRecommendationCount: 0,
    progressionJobId: null,
    restoredFromVersionId: null,
    restoredFromSnapshotId: null,
  };
  const snapshotEnvelope = {
    ...correctionEnvelope,
    category: "restore_snapshot",
    reasonNote: null,
    source: "snapshot_restore",
    decidedAt: "2026-08-01T17:00:00.000Z",
    sourceHistoryRevision: 1,
    resultHistoryRevision: 2,
    sourceLedgerRevision: 1,
    resultLedgerRevision: 2,
    dependentConclusions: "snapshot_state_reconciled",
    restoredFromSnapshotId: ids.snapshot,
  };

  await db.insert(recordVersions).values([
    {
      id: ids.correctionVersion,
      userId: ids.user,
      entityType: "completed_set",
      entityId: ids.importedSet,
      action: "set.completed_correction",
      beforeData: { id: ids.importedSet, reps: 10 },
      afterData: {
        id: ids.importedSet,
        reps: 12,
        repbook_correction: correctionEnvelope,
      },
      changedFields: ["reps"],
      createdAt: new Date("2026-08-01T16:00:00.000Z"),
    },
    {
      id: ids.snapshotRestoreVersion,
      userId: ids.user,
      entityType: "completed_set",
      entityId: ids.importedSet,
      action: "set.snapshot_restore",
      beforeData: { id: ids.importedSet, reps: 12 },
      afterData: {
        id: ids.importedSet,
        reps: 11,
        repbook_correction: snapshotEnvelope,
      },
      changedFields: ["reps"],
      createdAt: new Date("2026-08-01T17:00:00.000Z"),
    },
    {
      id: ids.timingCorrectionVersion,
      userId: ids.user,
      entityType: "workout_session",
      entityId: ids.finishedEarlySession,
      action: "workout_session.timing_correction",
      beforeData: {
        id: ids.finishedEarlySession,
        finished_at: "2026-08-02T14:18:00.000Z",
      },
      afterData: {
        id: ids.finishedEarlySession,
        finished_at: "2026-08-02T14:20:00.000Z",
      },
      changedFields: ["finished_at"],
      createdAt: new Date("2026-08-02T16:00:00.000Z"),
    },
  ]);

  console.log(`Seeded H01 History fixture for ${V2_H01_HISTORY_EMAIL}.`);
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
